"""redesign tooth_status to position-based dentition model

Revision ID: 3938cb64131c
Revises: 08fe781ea38a
Create Date: 2026-09-16 06:11:06.574500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3938cb64131c'
down_revision: Union[str, None] = '08fe781ea38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tooth_status', sa.Column('quadrant', sa.Integer(), nullable=False))
    op.add_column('tooth_status', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('tooth_status', sa.Column('dentition', sa.String(length=20), nullable=True))
    op.drop_constraint('uq_tooth_status_chart_tooth', 'tooth_status', type_='unique')
    op.create_unique_constraint('uq_tooth_status_chart_quadrant_position', 'tooth_status', ['dental_chart_id', 'quadrant', 'position'])
    op.drop_column('tooth_status', 'tooth_code')
    op.drop_column('tooth_status', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tooth_status', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tooth_status', sa.Column('tooth_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint('uq_tooth_status_chart_quadrant_position', 'tooth_status', type_='unique')
    op.create_unique_constraint('uq_tooth_status_chart_tooth', 'tooth_status', ['dental_chart_id', 'tooth_code'])
    op.drop_column('tooth_status', 'dentition')
    op.drop_column('tooth_status', 'position')
    op.drop_column('tooth_status', 'quadrant')
    # ### end Alembic commands ###
