"""initial schema

Revision ID: f5f15b2393d5
Revises: 
Create Date: 2026-09-07 04:50:38.825218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5f15b2393d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assignment_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', postgresql.ENUM('manual', 'auto', name='assignment_mode'), nullable=False),
    sa.Column('strategy', postgresql.ENUM('least_workload', 'round_robin', name='assignment_strategy'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_assignment_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliniccards_patients',
    sa.Column('cliniccards_patient_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliniccards_patients_cliniccards_patient_id'), 'cliniccards_patients', ['cliniccards_patient_id'], unique=True)
    op.create_table('image_types',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', postgresql.ENUM('extraoral', 'intraoral', 'radiology', name='image_category'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('integration_sync_log',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sync_type', postgresql.ENUM('poll', 'webhook', 'manual', name='sync_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'partial', 'error', name='sync_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('cases_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', postgresql.ENUM('on_assignment', 'before_consultation', 'after_deadline', name='reminder_trigger_type'), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('notify_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_workload', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_templates',
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('image_type_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_type', postgresql.ENUM('single_choice', 'multi_choice', 'boolean', 'text', 'measurement', name='answer_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measurement_required', sa.Boolean(), nullable=False),
    sa.Column('annotation_required', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=100), nullable=True),
    sa.Column('clinical_priority', sa.Integer(), nullable=True),
    sa.Column('presentation_text_template', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_type_id'], ['image_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_templates_image_type_id'), 'analysis_templates', ['image_type_id'], unique=False)
    op.create_table('cliniccards_appointments',
    sa.Column('cliniccards_appointment_id', sa.String(length=255), nullable=False),
    sa.Column('cliniccards_patient_id', sa.String(length=255), nullable=False),
    sa.Column('appointment_type_code', sa.String(length=255), nullable=True),
    sa.Column('appointment_type_label', sa.String(length=255), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliniccards_patient_id'], ['cliniccards_patients.cliniccards_patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliniccards_appointments_cliniccards_appointment_id'), 'cliniccards_appointments', ['cliniccards_appointment_id'], unique=True)
    op.create_index(op.f('ix_cliniccards_appointments_scheduled_at'), 'cliniccards_appointments', ['scheduled_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('super_admin', 'admin', 'planner', 'doctor', 'consultant', name='role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    op.create_table('cases',
    sa.Column('cliniccards_patient_id', sa.String(length=255), nullable=False),
    sa.Column('cliniccards_appointment_id', sa.String(length=255), nullable=False),
    sa.Column('consultation_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_doctor_user_id', sa.UUID(), nullable=True),
    sa.Column('primary_doctor_name', sa.String(length=255), nullable=True),
    sa.Column('responsible_planner_user_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'WAITING_ASSIGNMENT', 'ASSIGNED', 'IMAGES_READY', 'ANALYSIS_IN_PROGRESS', 'PLAN_IN_PROGRESS', 'REVIEW_REQUIRED', 'READY', 'CONSULTATION_COMPLETED', 'OVERDUE', name='case_status'), nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'urgent', name='priority'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('images_progress_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliniccards_appointment_id'], ['cliniccards_appointments.cliniccards_appointment_id'], ),
    sa.ForeignKeyConstraint(['cliniccards_patient_id'], ['cliniccards_patients.cliniccards_patient_id'], ),
    sa.ForeignKeyConstraint(['primary_doctor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_planner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliniccards_appointment_id')
    )
    op.create_index(op.f('ix_cases_cliniccards_patient_id'), 'cases', ['cliniccards_patient_id'], unique=False)
    op.create_index(op.f('ix_cases_consultation_datetime'), 'cases', ['consultation_datetime'], unique=False)
    op.create_index(op.f('ix_cases_responsible_planner_user_id'), 'cases', ['responsible_planner_user_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_case_id'), 'audit_log', ['case_id'], unique=False)
    op.create_table('clinical_images',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('image_type_id', sa.UUID(), nullable=True),
    sa.Column('source', postgresql.ENUM('cliniccards', 'upload', name='image_source'), nullable=False),
    sa.Column('cliniccards_document_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_type_id'], ['image_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'cliniccards_document_id', name='uq_clinical_images_case_doc')
    )
    op.create_index(op.f('ix_clinical_images_case_id'), 'clinical_images', ['case_id'], unique=False)
    op.create_index(op.f('ix_clinical_images_image_type_id'), 'clinical_images', ['image_type_id'], unique=False)
    op.create_table('dental_charts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('numbering_system', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('notifications',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('presentations',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('format', postgresql.ENUM('pptx', 'pdf', name='presentation_format'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('template_version', sa.String(length=50), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_case_id'), 'presentations', ['case_id'], unique=False)
    op.create_table('reminder_sent_log',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'rule_id', name='uq_reminder_sent_case_rule')
    )
    op.create_table('treatment_plans',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('plan_label', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_case_id'), 'treatment_plans', ['case_id'], unique=False)
    op.create_table('analysis_answers',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('answer_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measurement_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('answered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['clinical_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['analysis_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_answers_case_id'), 'analysis_answers', ['case_id'], unique=False)
    op.create_index(op.f('ix_analysis_answers_image_id'), 'analysis_answers', ['image_id'], unique=False)
    op.create_table('image_annotations',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('annotation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['clinical_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_annotations_image_id'), 'image_annotations', ['image_id'], unique=False)
    op.create_table('tooth_status',
    sa.Column('dental_chart_id', sa.UUID(), nullable=False),
    sa.Column('tooth_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dental_chart_id'], ['dental_charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dental_chart_id', 'tooth_code', name='uq_tooth_status_chart_tooth')
    )
    op.create_index(op.f('ix_tooth_status_dental_chart_id'), 'tooth_status', ['dental_chart_id'], unique=False)
    op.create_table('treatment_plan_versions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_no', name='uq_plan_version')
    )
    op.create_index(op.f('ix_treatment_plan_versions_plan_id'), 'treatment_plan_versions', ['plan_id'], unique=False)
    op.create_table('findings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('source_image_id', sa.UUID(), nullable=True),
    sa.Column('source_answer_id', sa.UUID(), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_answer_id'], ['analysis_answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_image_id'], ['clinical_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_table('reviews',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('plan_version_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('decision', postgresql.ENUM('approve', 'revision_required', name='review_decision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['treatment_plan_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_case_id'), 'reviews', ['case_id'], unique=False)
    op.create_table('treatment_problems',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_problems_case_id'), 'treatment_problems', ['case_id'], unique=False)
    op.create_table('treatment_objectives',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('objective_text', sa.Text(), nullable=False),
    sa.Column('proposed_action', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['treatment_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_objectives_problem_id'), 'treatment_objectives', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_objectives_problem_id'), table_name='treatment_objectives')
    op.drop_table('treatment_objectives')
    op.drop_index(op.f('ix_treatment_problems_case_id'), table_name='treatment_problems')
    op.drop_table('treatment_problems')
    op.drop_index(op.f('ix_reviews_case_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_treatment_plan_versions_plan_id'), table_name='treatment_plan_versions')
    op.drop_table('treatment_plan_versions')
    op.drop_index(op.f('ix_tooth_status_dental_chart_id'), table_name='tooth_status')
    op.drop_table('tooth_status')
    op.drop_index(op.f('ix_image_annotations_image_id'), table_name='image_annotations')
    op.drop_table('image_annotations')
    op.drop_index(op.f('ix_analysis_answers_image_id'), table_name='analysis_answers')
    op.drop_index(op.f('ix_analysis_answers_case_id'), table_name='analysis_answers')
    op.drop_table('analysis_answers')
    op.drop_index(op.f('ix_treatment_plans_case_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_table('reminder_sent_log')
    op.drop_index(op.f('ix_presentations_case_id'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('dental_charts')
    op.drop_index(op.f('ix_clinical_images_image_type_id'), table_name='clinical_images')
    op.drop_index(op.f('ix_clinical_images_case_id'), table_name='clinical_images')
    op.drop_table('clinical_images')
    op.drop_index(op.f('ix_audit_log_case_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_responsible_planner_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_consultation_datetime'), table_name='cases')
    op.drop_index(op.f('ix_cases_cliniccards_patient_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_cliniccards_appointments_scheduled_at'), table_name='cliniccards_appointments')
    op.drop_index(op.f('ix_cliniccards_appointments_cliniccards_appointment_id'), table_name='cliniccards_appointments')
    op.drop_table('cliniccards_appointments')
    op.drop_index(op.f('ix_analysis_templates_image_type_id'), table_name='analysis_templates')
    op.drop_table('analysis_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reminder_rules')
    op.drop_table('integration_sync_log')
    op.drop_table('image_types')
    op.drop_index(op.f('ix_cliniccards_patients_cliniccards_patient_id'), table_name='cliniccards_patients')
    op.drop_table('cliniccards_patients')
    op.drop_table('assignment_config')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
