"""add file storage columns to clinical_images for manual uploads

Revision ID: facc529edd2a
Revises: 970995590f0f
Create Date: 2026-09-16 06:42:48.243185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facc529edd2a'
down_revision: Union[str, None] = '970995590f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_images', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('clinical_images', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('clinical_images', sa.Column('original_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_images', 'original_filename')
    op.drop_column('clinical_images', 'mime_type')
    op.drop_column('clinical_images', 'file_data')
    # ### end Alembic commands ###
